### PR TITLE
1. Fix the problem

### PR DESCRIPTION
**Pull request by huangjixin1997**
1.  Fix the problem of positioning deviation when scaling the high-resolution screen;
2.  Removes shadow boundaries around JavaFX ContextMenu.

### CODE REVIEW

**Comment by xdsswar** [comment]
@huangjixin1997
Thanks for your request, I'm testing with a 4k monitor and everything looks fine , can you share a screenshot or something?

**Comment by huangjixin1997** [comment]
Test environment:

- OS：Window 10 & Window 11
- JDK：openjdk 11
- Scaling：125%
- Resolution：2560  * 1440

image

**Comment by huangjixin1997** [comment]
Scaling：100%

image

**Comment by xdsswar** [comment]
@huangjixin1997 Thanks. I'm doing a very large project this days, but I will take a look and fix this issue as soon as I can.

**Pull request closed without merging**
